name: Build release from tag

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          repository: calaos/calaos-build
          event-type: build_pkg
          client-payload: '{"pkgname": "calaos-ddns", "repo": "calaos", "arch": "${{ github.event.inputs.arch }}", "version": "${{ github.ref_name }}", "commit": "${{ github.sha }}" }'
