name: Build dev and release deb package

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      vincrement:
        description: 'Package version increment (major.minor.xxx)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  build-and-push-deb-pkg:
    name: Build deb package and push to repositories
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Calaos Action Bump Version
        id: calaos_version
        uses: calaos/action-bump-version@2
        with:
          version_fragment: ${{ github.event.inputs.vincrement || 'prerelease' }}

      - name: Build package
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/calaos/debian_deb_build_base
          options: -v ${{ github.workspace }}:/work
          run: |
            /build-deb.sh ${{ steps.calaos_version.outputs.version_bumped }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: deb
          path: pkg/*.deb

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.calaos_version.outputs.version_bumped }}
          token: ${{ secrets.ACTION_DISPATCH }}

      - name: Create a Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.ACTION_DISPATCH }}
          tag: ${{ steps.calaos_version.outputs.version_bumped }}
          name: ${{ steps.calaos_version.outputs.version_bumped }}
          files: pkg/*.deb
          gzip: false

      - name: Update repo cache
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}